// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MongoDB_DotNetCore.data;

#nullable disable

namespace MongoDB_DotNetCore.Migrations
{
    [DbContext(typeof(SQLDatabaseContext))]
    [Migration("20241130105323_initial3")]
    partial class initial3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_Alarm_History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L0Name")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("L1Name")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("level")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("number")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double>("timespan")
                        .HasColumnType("float");

                    b.Property<string>("type")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Alarm_History");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_L1Signal_Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L1Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("signalname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double>("timespan")
                        .HasColumnType("float");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("value")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("L1Signal_Pool");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_L1Signal_Pool_Capped", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L1Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("signalname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double?>("timespan")
                        .HasColumnType("float");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("value")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("L1Signal_Pool_Capped");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_L1_Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L1Name")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("signalname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double?>("timespan")
                        .HasColumnType("float");

                    b.Property<string>("updatedate")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("value")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("L1_Pool");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_LatestCapturedEndDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LatestCapturedEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("collectionName")
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("LatestCapturedEndDate");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_Operator_History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L1Name")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("signalname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double?>("timespan")
                        .HasColumnType("float");

                    b.Property<string>("updatedate")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("value")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Operator_History");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_ProductResult_History", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("L1Name")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("productname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<int>("productresult")
                        .HasColumnType("int");

                    b.Property<int>("productresult_accumulate")
                        .HasColumnType("int");

                    b.Property<int>("resultflag")
                        .HasColumnType("int");

                    b.Property<double?>("timespan")
                        .HasColumnType("float");

                    b.Property<string>("updatedate")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("ProductResult_History");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_SystemDiagnosis_Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CycleTime")
                        .HasColumnType("int");

                    b.Property<int?>("ExecuteTime")
                        .HasColumnType("int");

                    b.Property<string>("MachineName")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("PCName")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Updatedate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SystemDiagnosis_Machine");
                });

            modelBuilder.Entity("MongoDB_DotNetCore.Entities.MSSQL.Sql_Tag_Pool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ObjectId")
                        .HasMaxLength(64)
                        .HasColumnType("NVARCHAR");

                    b.Property<string>("TagName")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<DateTime?>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("signalname")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.Property<double>("timespan")
                        .HasColumnType("float");

                    b.Property<DateTime?>("updatedate")
                        .HasColumnType("datetime2");

                    b.Property<string>("value")
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Tag_Pool");
                });
#pragma warning restore 612, 618
        }
    }
}
